### ISSUE TITLE
Feature request: add support for EchoPingHttps

### ISSUE THREAD

**Issue by Tony2** [linuxserver/docker-smokeping#116]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

users should be able to  use EchoPingHttps 

## Current Behavior

EchoPingHttps requires binary `echoping`, which is not included in the docker image.

## Alternatives Considered

I tried to install `echoping` with `apk`, but could not, it seems `echoping` is not available for alpine.

It would be helpful to have an extra  Dockerfile based on debian-slim, rather than alpine.

**Comment by sopelt** [comment]
Hi, seeing that there was https://github.com/linuxserver/docker-smokeping/issues/20 and https://github.com/linuxserver/docker-smokeping/issues/103 before this should be handled in some way. Yes, [echoping](https://framagit.org/bortzmeyer/echoping) seems stale and no longer actively maintained ... there are still packages for some distributions but not alpine.

Could someone document the situation in the readme of this repo so that users are aware that not all probes are available? tcpping might be an alternative for some use-cases...

Or the Dockerfile could be extended to build echoping.

**Comment by AliMickey** [comment]
Would benefit from this as well as I need to do some UDP testing.
