### ISSUE TITLE
[BUG] Dropping armhf support

### ISSUE THREAD

**Issue by mvnixon** [linuxserver/docker-smokeping#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Folks, any context as to why you have dropped armhf support?

### Steps To Reproduce

updated to latest build. 

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by thespad** [comment]
https://www.linuxserver.io/armhf

**Comment by mvnixon** [comment]
" year ago, around 2/3 of our Arm users were still on 32-bit platforms, today it's less than 1/5, and consequently we have taken the difficult decision to formally deprecate 32-bit Arm builds from 2023-07-01"

Bit early?

**Comment by thespad** [comment]
> Due to the number of images and how our build pipelines work there's going to be some wiggle room here.

In this instance, there was a vocal demand to move to our newest base image (Alpine 3.18) to provide a newer version of Smokeping because it had been sitting on 2.7 for several years, so it got prioritised for updating, but there's no armhf variant of that base image (because there was no point with less than 3 months between its creation and the dropping of support).

**Comment by j0nnymoe** [comment]
A bit early? Maybe. Does it make any difference to armhf users? No because the image that's currently out wouldn't of had any updates anyways.
